[versions]
agp = "8.2.2"
kotlin = "1.8.20"
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
asm = "9.3"
constraintlayout = "2.1.4"
aliyun-log = "2.7.14"
kotlin-coroutines-android = "1.6.4"
firebase-analytics-ktx = "21.3.0"
gson = "2.8.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm" }
asm-util = { group = "org.ow2.asm", name = "asm-util", version.ref = "asm" }
android-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp"}
jetbrains-kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin"}
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
aliyun-log-android = { group = "io.github.aliyun-sls", name = "aliyun-log-android-sdk", version.ref = "aliyun-log" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines-android"}
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

